---
# tasks file for common

#- name: setup app user
#  user: generate_ssh_key=yes name={{action_user}} password={{action_user_pw | password_hash('sha512')}} shell=/bin/bash

- name: install yum utilities
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
#    - epel-release
  become: yes

#- name: install htop
#  yum: name: 

- name: install other basic os utilities
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
    - tmux
    - wget
    - curl
    - git
    - tree
    - rsync
    - zsh
  become: yes


