---
# tasks file for yum_repo setup over http

- name: allow web on firewalld
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: yes

- name: install packages needed for repo
  yum: 
    name: "{{ item }}"
    state: present
  with_items: 
    - httpd
    - createrepo
  notify: restart httpd

- name: create httpd virtual host configuration
  template:
    src: virtualhost.conf.j2
    dest: /etc/httpd/conf.d/virtualhost.conf

- name: create dirs for repo
  file: 
    path: "{{ yum_server_repo_path }}"
    owner: apache
    group: apache
    seuser: system_u
    serole: object_r
    setype: httpd_sys_content_t
    state: directory

- import_tasks: update_epel_pkgs.yaml
- import_tasks: update_docker_pkgs.yaml


