---
- name: copy docker packages and repos to server
  copy:
    src: "{{ yum_repo_src_path }}/docker-ce/"
    dest: "{{ yum_server_repo_path }}/docker-ce/"
    mode: '0775'
    owner: apache
    group: apache
    seuser: system_u
    serole: object_r
    setype: httpd_sys_content_t
  notify: restart httpd

- name: set correct permission to expose epel-addon repodata over http
  file:
    dest: "{{ yum_server_repo_path }}"
    mode: '0775'
    owner: apache
    group: apache
    seuser: system_u
    serole: object_r
    setype: httpd_sys_content_t
    

