#
# Global variables for all nodes
#
---

HOST_ARCH: amd64

# indicate if servers are air-gap and thus, 
# has access to yum repository over internet
is_online: false

# indicate if repo containing older docker-engine 
# should be used instead of that containing docker-ce
use_legacy_docker_repo: no

# the version of docker compose 
# to be installed or used
docker_compose_version: 1.21.0

# the full path to the stored yum packages
# that will be copied to the http server
# running yum repo
yum_repo_src_path: /binaries/

# the actual path of the yum repo
# that contains the packages
# on the http server.
# -- Note: Should not end with '/'
yum_server_repo_path: /data/repo
