---
- name: copy pip packages and repos to server
  copy:
    src: "{{ yum_repo_src_path }}/pip/"
    dest: "{{ yum_server_repo_path }}/pip/"
    mode: '0775'
    owner: apache
    group: apache
    seuser: system_u
    serole: object_r
    setype: httpd_sys_content_t
  notify: restart httpd

