---
# tasks file for docker

- name: install docker-py
  pip:
    name: "docker[tls]" 
    extra_args: "-v --no-index --trusted-host {{ yum_server }} --find-links http://{{ yum_server }}/repo/pip/docker-py/"
    state: present
  become: yes

- include_tasks: "{{ is_online | ternary('online', 'offline') }}_docker_repo.yaml"

- name: install docker dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - device-mapper-persistent-data
    - lvm2
  become: yes
 
- name: disable obsoletes option to workaround installation of older docker versions
  ini_file:
    path: /etc/yum.conf
    section: main
    option: obsoletes
    value: 0
  become: yes
 
- name: install docker
  yum:
    name: "docker-ce-{{ docker_version }}"
    state: present
  become: yes
  notify: restart docker

- name: get user running ansible
  local_action: command whoami
  register: remote_user
  become: no

- name: determine docker administrator (app user)
  set_fact:
    docker_user: "{{ ansible_user | default(remote_user.stdout) }}"

- name: add administrator (app user) to docker group
  user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes
  become: yes

- import_tasks: install_docker_compose.yaml

